### ISSUE TITLE
After one iter training speed become very slow

### ISSUE THREAD

**Issue by House-Leo** [LiJunnan1992/MLNT#4]
![微信截图_20191107154400](https://user-images.githubusercontent.com/47940711/68369563-9755b780-0175-11ea-824a-d6561882995a.png)
pytorch version = 1.2.0 
Tesla v100
CUDA 10.0

I thing your envirment is pytorch<0.4.0, so I have to change code in order to run it. 
The baseline.py has no problem, but the main.py has.

**Comment by LiJunnan1992** [comment]
I'm not sure why it happens, does the speed increase with a smaller num_fast?
